/dev/mapper/LVMVolGroup-data                                    7.0T  2.5T  4.2T  38% /var/openebs
/dev/sda3                                                       219G  155G   53G  75% /
/dev/mapper/LVMVolGroup-data                                     224M   17M  208M    8% /var/openebs
/dev/sda3                                                         14M  2.9M   12M   21% /
devstats-prod    devstats-api-98c59f8b7-k42d4                                    1/1     Running       0          52d
devstats-test    devstats-all-1649433840-br7xz                                   1/1     Running       0          55m
devstats-test    devstats-api-66d4649f7f-jm245                                   1/1     Running       0          57m
devstats-test    devstats-confidentialcontainers-1649437140-mm8rp                1/1     Running       0          2m17s
Test status:
Prod status:
2022-04-08 16:41:34 graphql/gha2db: Error(time=2022-04-08 16:41:34.03953151 +0000 UTC m=+12.221498335):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:41:34.03953151 +0000 UTC m=+12.221498335):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:42:34 graphql/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:42:34 graphql/gha2db_sync: Error(time=2022-04-08 16:42:34.149079216 +0000 UTC m=+72.394055480):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:42:34.149079216 +0000 UTC m=+72.394055480):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:43:34 /devstats: Error result for graphql (took 2m12.436278417s): exit status 2
2022-04-08 16:43:34.18963576 +0000 UTC m=+135.711099578: Error result for graphql (took 2m12.436278417s): exit status 2
2022-04-08 16:39:57 graphqljs/gha2db: Error(time=2022-04-08 16:39:57.947417405 +0000 UTC m=+52.023464647):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:39:57.947417405 +0000 UTC m=+52.023464647):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:40:58 graphqljs/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:40:58 graphqljs/gha2db_sync: Error(time=2022-04-08 16:40:58.053615256 +0000 UTC m=+112.194748099):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:40:58.053615256 +0000 UTC m=+112.194748099):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:41:58 /devstats: Error result for graphqljs (took 2m52.258916629s): exit status 2
2022-04-08 16:41:58.115895353 +0000 UTC m=+173.278496757: Error result for graphqljs (took 2m52.258916629s): exit status 2
2022-04-08 16:39:38 graphiql/get_repos: Error(time=2022-04-08 16:39:38.673328674 +0000 UTC m=+0.044042394):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:39:38.673328674 +0000 UTC m=+0.044042394):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:40:38 graphiql/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:40:38 graphiql/gha2db_sync: Error(time=2022-04-08 16:40:38.724693042 +0000 UTC m=+93.241459377):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:40:38.724693042 +0000 UTC m=+93.241459377):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:41:38 /devstats: Error result for graphiql (took 2m33.247539274s): exit status 2
2022-04-08 16:41:38.729193107 +0000 UTC m=+154.166572898: Error result for graphiql (took 2m33.247539274s): exit status 2
2022-04-08 16:42:00 expressgraphql/get_repos: Error(time=2022-04-08 16:42:00.915090833 +0000 UTC m=+0.064664403):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:42:00.915090833 +0000 UTC m=+0.064664403):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:43:00 expressgraphql/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:43:00 expressgraphql/gha2db_sync: Error(time=2022-04-08 16:43:00.978878353 +0000 UTC m=+102.575131025):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:43:00.978878353 +0000 UTC m=+102.575131025):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:44:01 /devstats: Error result for expressgraphql (took 2m42.6804009s): exit status 2
2022-04-08 16:44:01.082577634 +0000 UTC m=+163.546113613: Error result for expressgraphql (took 2m42.6804009s): exit status 2
2022-04-08 16:41:09 graphqlspec/get_repos: Error(time=2022-04-08 16:41:09.966384116 +0000 UTC m=+0.020316676):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:41:09.966384116 +0000 UTC m=+0.020316676):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:42:10 graphqlspec/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:42:10 graphqlspec/gha2db_sync: Error(time=2022-04-08 16:42:10.030619391 +0000 UTC m=+117.254926932):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:42:10.030619391 +0000 UTC m=+117.254926932):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:43:10 /devstats: Error result for graphqlspec (took 2m57.263487705s): exit status 2
2022-04-08 16:43:10.037338159 +0000 UTC m=+178.231003814: Error result for graphqlspec (took 2m57.263487705s): exit status 2
2022-04-08 16:36:44 spinnaker/gha2db: Error(time=2022-04-08 16:36:44.881538723 +0000 UTC m=+45.497327188):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:36:44.881538723 +0000 UTC m=+45.497327188):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:37:45 spinnaker/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:37:45 spinnaker/gha2db_sync: Error(time=2022-04-08 16:37:45.052811015 +0000 UTC m=+105.761831963):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:37:45.052811015 +0000 UTC m=+105.761831963):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:38:45 /devstats: Error result for spinnaker (took 2m45.816445447s): exit status 2
2022-04-08 16:38:45.105886089 +0000 UTC m=+173.453541075: Error result for spinnaker (took 2m45.816445447s): exit status 2
2022-04-08 16:35:29 tekton/gha2db: Error(time=2022-04-08 16:35:29.447840357 +0000 UTC m=+41.810085113):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
Error(time=2022-04-08 16:35:29.447840357 +0000 UTC m=+41.810085113):
Error: 'pq: relation "gha_reviews" does not exist'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:36:29 tekton/gha2db_sync: ErrorType: *exec.ExitError, error: exit status 2
2022-04-08 16:36:29 tekton/gha2db_sync: Error(time=2022-04-08 16:36:29.643502135 +0000 UTC m=+102.068545645):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:58 +0x99d
ErrorType: *exec.ExitError, error: exit status 2
Error(time=2022-04-08 16:36:29.643502135 +0000 UTC m=+102.068545645):
Error: 'exit status 2'
	/go/src/github.com/cncf/devstatscode/error.go:63 +0xb67
2022-04-08 16:37:29 /devstats: Error result for tekton (took 2m42.128430458s): exit status 2
2022-04-08 16:37:29.700195029 +0000 UTC m=+164.563261863: Error result for tekton (took 2m42.128430458s): exit status 2
------------
R
